// Local Routes
// GET Routes
GET http://localhost:3000/contacts/all
###
GET http://localhost:3000/contacts/650ab257f809c6756bf2d83e
###
GET http://localhost:3000/contacts/650ab7f9f809c6756bf2d840
###
GET http://localhost:3000/contacts/650ab816f809c6756bf2d841

// POST Route
###
POST http://localhost:3000/contacts/add
content-type: application/json

{
        "firstName": "Elizabeth",
        "lastName": "Beatty",
        "email": "Not Present",
        "favoriteColor": "Green",
        "birthday": "Jul 29"
}

// PUT Route
// Remember to paste the desired ID into the end of this.
###
PUT http://localhost:3000/contacts/65160fbac396764d5437404e
content-type: application/json

{
        "firstName": "Zoe",
        "lastName": "Beatty",
        "email": "Not Present",
        "favoriteColor": "Unknown",
        "birthday": "Unknown"
}

// DELETE Route
// Remember to paste the desired ID into the end of this.
###
DELETE http://localhost:3000/contacts/65160fbac396764d5437404e

// Deployment Routes
// GET Routes
###
GET https://cse-341-zwc9.onrender.com/contacts/all
###
GET https://cse-341-zwc9.onrender.com/contacts/650ab257f809c6756bf2d83e
###
GET https://cse-341-zwc9.onrender.com/contacts/650ab7f9f809c6756bf2d840
###
GET https://cse-341-zwc9.onrender.com/contacts/650ab816f809c6756bf2d841

// POST Route
###
POST https://cse-341-zwc9.onrender.com/contacts/add
content-type: application/json

{
        "firstName": "Elizabeth",
        "lastName": "Beatty",
        "email": "Not Present",
        "favoriteColor": "Green",
        "birthday": "Jul 29"
}

// PUT Route
// Remember to paste the desired ID into the end of this.
###
PUT https://cse-341-zwc9.onrender.com/contacts/6514af8189a12f37f34d6298
content-type: application/json

{
        "firstName": "Zoe",
        "lastName": "Beatty",
        "email": "Not Present",
        "favoriteColor": "Unknown",
        "birthday": "Unknown"
}

// DELETE Route
// Remember to paste the desired ID into the end of this.
###
DELETE https://cse-341-zwc9.onrender.com/contacts/6514af8189a12f37f34d6298